export const dict = {
  fa : {
    'overview': 'نمای کلی',
    'events': 'رویدادها',
    'home': 'خانه',
    'meetings': 'نشست ها',
    'users': 'کاربران',

    'event_detail':'جزئیات رویداد',
    'event_title':'عنوان رویداد',
    'event_info':'شرح رویداد',
    'event_type':'نوع رویداد',
    'event':'رویداد',
    'create_event':'ایجاد رویداد',
    'create_event_page':'ایجاد رویداد',
    'in_person': 'حضوری',
    'online': 'برخط',
    'hybrid': 'تلفیقی',
    'filter_events':'جستجو و فیلتر رویدادها',

    'meeting_info':'شرح نشست',
    'meeting_title':'عنوان نشست',
    'meeting_detail':'جزئیات نشست',
    'meeting_type':'نوع نشست',
    'meeting_capacity': 'ظرفیت نشست',
    'meeting_external_link': 'لینک نشست',
    'meeting_start_time': 'زمان شروع',
    'meeting_end_time': 'زمان پایان',
    'related_to_event': 'نشستی از رویداد',
    'create_meeting':'ایجاد نشست',
    'create_meeting_page':'ایجاد نشست',
    'online_external': 'برخط بیرونی',
    'filter_meetings': 'جستجو و فیلتر نشست ها',
    

    'exhibition_info':'شرح',
    'exhibition_detail': 'جزئیات غرفه',
    'exhibition_title':'عنوان شرکت/موسسه',
    'related_to_event': 'مربوط به رویداد',
    'create_exhibition':'ایجاد غرفه',
    'create_exhibition_page':'ایجاد غرفه',
    'exhibitions': 'نمایشگاه',
    'stations': 'غرفه ها',
    'enter_room_with_admin': 'مذاکره با غرفه دار',

    'choose_participants': 'شرکت کنندگان موردنظر را انتخاب کنید',
    'participants':'شرکت کنندگان',
    'add_participants': 'افزودن شرکت کننده',

    'pages':'صفحات',
    'page_content':'محتوای صفحه',
    'page_title':'عنوان صفحه',
    'create_page':'ایجاد صفحه',
    'default_page':'صفحه پیش فرض',
    'default_page_info':'این صفحه به عنوان پیش فرص در نشست نمایش داده شود',

    'create_upload':'بارگزاری منبع',
    'upload_title':'عنوان منبع',
    'default_is_private_upload':'به جز مدیران فایل ها دیده نشود',
    'cover': 'کاور',
    'file' : 'فایل',
    'video': 'ویدیو',
    'choose_file': 'انتخاب فایل',
    'resources': 'منابع',
    'all': 'همه',

    'q_and_a_s': 'پرسش و پاسخ ها',
    'create_question_page':'ثبت پرسش',
    'create_question':'ثبت پرسش',
    'question_content':'متن پرسش',
    'default_is_private_question':'پرسش فقط توسط مدیران دیده شود',
    '':'',

    'chats': 'گفتگوها',
    'details':'جزئیات',
    'welcome':'خوش آمدید',
    'welcome_note':'با ورود به این سامانه می توانید رویدادهای خود را مدیریت کنید یا در سایر رویداد ها شرکت کنید.',
    'sign_up_now':'هم اکنون ثبت نام کنید',
    'your_email':'ایمیل',
    'your_name':'نام کامل',
    'choose_password':'انتخاب رمزعبور',
    'repeat_password':'تکرار رمزعبور',
    'password_rule':'رمزعبور حتما باید ۸ رقمی باشد',
    'sign_up_and_continue':'ثبت نام و ادامه',
    'login_if_registered':'اگر قبلا ثبت نام کرده اید',
    'if_not_registered': 'اگر ثبت نام نکرده اید',
    'login':'وارد شوید',
    'sign_up':'ثبت نام کنید',
    'password':'رمز عبور',
    'enter_bigblue_room':'ورود به اتاق تعامل',
    '':'',

    'cas':'احراز هویت مرکزی',
    'more':'بیشتر',
    'date_from':'از تاریخ',
    'date_to':'تا تاریخ',
    'logout':'خروج',
    'write_something':'اینجا بنویسید ...',
    'provide_following_info':'اطلاعات زیر را تکمیل کنید',
    'cancel':'انصراف',
    'submit':'ثبت',    
    'filter':'فیلتر کن',
    'search_placeholder':'جستجو...',
    'contains_words': 'شامل حروف',
    'save':'ذخیره',
    'filter_and_search':'فیلتر و جستجو',
    'tags': 'برچسب ها',
    'is_private':'خصوصی',
    'speakers': 'صحبت کنندگان',
    'listeners': 'شنوندگان',
    'moderator': 'مدیر',
    'listener': 'شنونده',
    'presenter': 'ارائه دهنده',
    'speaker': 'صحبت کننده',
    'calendar':'تقویم',
    'enter_room': 'ورود به جلسه',
    'default_is_private_info':'کاربران نمیتوانند خودشان در رویداد ها یا نشست های خصوصی عضو شوند و صرفا باید دعوت شوند',
  }

}
