export const dict = {
  'farsi' : {
    'overview': 'نمای کلی',
    'events': 'رویدادها',
    'home': 'خانه',
    'meetings': 'نشست ها',
    'users': 'کاربران',
    'your_country': 'کشور',
    'bio':'درباره من',
    'write_about_yourself': 'درباره خودتان بنویسید ...',
    'complete_your_profile':'اطلاعات خود را تکمیل کنید',
    'continue': 'ادامه',
    'profiles': 'کاربران',
    'settings':'تنظیمات',

    'event_detail':'جزئیات رویداد',
    'event_title':'عنوان رویداد',
    'event_info':'شرح رویداد',
    'event_type':'نوع رویداد',
    'event':'رویداد',
    'create_event':'ایجاد رویداد',
    'create_event_page':'ایجاد رویداد',
    'in_person': 'حضوری',
    'online': 'برخط',
    'hybrid': 'تلفیقی',
    'filter_events':'جستجو و فیلتر رویدادها',
    'event_start_date': 'تاریخ شروع',
    'event_end_date':'تاریخ پایان',

    'abilities':'امکانات کاربران',
    'restrictions':'محدودیت های کاربران',
    'reports':'گزارشات',
    '':'',
    
    'meeting_info':'شرح نشست',
    'meeting_title':'عنوان نشست',
    'meeting_detail':'جزئیات نشست',
    'meeting_type':'نوع نشست',
    'meeting_capacity': 'ظرفیت نشست',
    'meeting_external_link': 'لینک نشست',
    'meeting_start_time': 'زمان شروع',
    'meeting_end_time': 'زمان پایان',
    'related_to_event': 'نشستی از رویداد',
    'create_meeting':'ایجاد نشست',
    'create_meeting_page':'ایجاد نشست',
    'online_external': 'برخط بیرونی',
    'filter_meetings': 'جستجو و فیلتر نشست ها',
    'service_type':'نوع سرویس جلسات',
    'internal':'درون سامانه',
    'bigblue':'بیگ بلو باتن',
    

    'exhibition_info':'شرح',
    'exhibition_detail': 'جزئیات غرفه',
    'exhibition_title':'عنوان شرکت/موسسه',
    'related_to_event': 'مربوط به رویداد',
    'create_exhibition':'ایجاد غرفه',
    'create_exhibition_page':'ایجاد غرفه',
    'exhibitions': 'نمایشگاه',
    'stations': 'غرفه ها',
    'enter_room_with_admin': 'مذاکره با غرفه دار',

    'choose_participants': 'شرکت کنندگان موردنظر را انتخاب کنید',
    'participants':'شرکت کنندگان',
    'add_participants': 'افزودن شرکت کننده',

    'pages':'صفحات',
    'page_content':'محتوای صفحه',
    'page_title':'عنوان صفحه',
    'create_page':'ایجاد صفحه',
    'default_page':'صفحه پیش فرض',
    'default_page_info':'این صفحه به عنوان پیش فرص در نشست نمایش داده شود',

    'create_upload':'بارگزاری منبع',
    'upload_title':'عنوان منبع',
    'default_is_private_upload':'به جز مدیران فایل ها دیده نشود',
    'cover': 'کاور',
    'file' : 'فایل',
    'video': 'ویدیو',
    'choose_file': 'انتخاب فایل',
    'resources': 'منابع',
    'all': 'همه',
    'resource_type': 'نوع منبع',

    'q_and_a_s': 'پرسش و پاسخ ها',
    'create_question_page':'ثبت پرسش',
    'create_question':'ثبت پرسش',
    'question_content':'متن پرسش',
    'default_is_private_question':'پرسش فقط توسط مدیران دیده شود',
    '':'',

    'chats': 'گفتگو',
    'details':'جزئیات',
    'welcome':'خوش آمدید',
    'welcome_note':'با ورود به این سامانه می توانید رویدادهای خود را مدیریت کنید یا در سایر رویداد ها شرکت کنید.',
    'sign_up_now':'هم اکنون ثبت نام کنید',
    'your_email':'ایمیل',
    'your_name':'نام کامل',
    'choose_password':'انتخاب رمزعبور',
    'repeat_password':'تکرار رمزعبور',
    'password_rule':'رمزعبور حتما باید ۸ رقمی باشد',
    'sign_up_and_continue':'ثبت نام و ادامه',
    'login_if_registered':'اگر قبلا ثبت نام کرده اید',
    'if_not_registered': 'اگر ثبت نام نکرده اید',
    'login':'وارد شوید',
    'sign_up':'ثبت نام کنید',
    'password':'رمز عبور',
    'enter_bigblue_room':'ورود به اتاق تعامل',
    '':'',

    'poll_content':'متن پرسش نظرسنجی',
    'single_select':'چندگزینه تک انتخاب',
    'multiple_select':'چند گزینه چند انتخاب',
    'star':'ستاره',
    'binary':'بلی/خیر',
    'trinary':'موافق/مخالف/ممتنع',
    'answer_type':'نوع پاسخ',
    'select_content':'پاسخ های چند گزینه ای',
    'separate_with_enter':'با دکمه enter پاسخ ها را جدا کنید.',
    'polls':'نظرسنجی',

    'just_listen_click':'اگر فقط مایل به شنیدن هستید کلیک کنید',
    'piano1':'پیانو ۱',
    'piano2':'پیانو ۲',
    'ended':'تمام',
    'quran':'قرآن',
    'applause1':'تشویق',
    'applause2':'تشویق گروهی',
    'laugh':'خنده',
    'laughing':'قهقهه',
    'snoring':'خر و پف',
    'throat':'صاف کردن صدا',
    'footsteps':'صدای پا',
    'play_sound':'پخش صدا در جلسه',
    'remaining':'باقیمانده',
    'seconds':'ثانیه',
    'anthem-iran': 'سرود ملی ایران',
    'Permission denied': 'مجوز دسترسی به میکروفن یا دوربین داده نشده است',
    'error': 'خطا',
    'sata': 'ساتا',
    'close': 'بستن',
    'maximize': 'بزرگنمایی',
    'yes': 'بله',
    'no': 'خیر',
    'abstention':'ممتنع',
    'viewers': 'حاضرین',
    'my_calendar':'تقویم من',
    'registeration':'وضعیت ثبت نام',
    'registered':'ثبت نام شده',
    'not_registered':'ثبت نام نشده',
    'are_you_sure':'آیا مطمئن هستید؟',
    'delete':'حذف',
    'true':'مثبت',
    'false':'منفی',
    'create_event':'ایجاد رخداد',
    'create_exhibition':'ایجاد غرفه',
    'modify_ability':'تغییر امکانات کاربران',
    'administration':'مدیریت تنظیمات',
    'view':'نمایش',
    'out_of_time':'خارج از زمان نشست',
    'room_is_full':'اتاق پر است',
    'unregister': 'لغو ثبت نام',
    'register':'ثبت نام',
    'check_your_spam_folder': 'در صورت عدم مشاهده، پوشه spam را هم بررسی کنید',
    'your_account_is_not_verified': 'لطفا کد تایید را که برای شما ایمیل شده است وارد کنید',
    'verfication_code': 'کد فعالسازی',
    'email':'ایمیل',
    'name':'نام کامل',
    'password':'رمزعبور',
    'password_confirmation':'تکرار رمز عبور',
    'file':'فایل',
    'info': 'شرح',
    'title': 'عنوان',
    'the_following_should_not_be_empty': 'مقادیر زیر نمی تواند خالی باشد',
    'error':'خطا',
    'no_result_to_show':'موردی برای نمایش وجود ندارد',
    'try_adjusting_your_search':'لطفا موارد جستجو رو مجددا بررسی کنید',
    'cas':'احراز هویت مرکزی',
    'more':'بیشتر',
    'date_from':'از تاریخ',
    'date_to':'تا تاریخ',
    'logout':'خروج',
    'write_something':'اینجا بنویسید ...',
    'provide_following_info':'اطلاعات زیر را تکمیل کنید',
    'cancel':'انصراف',
    'submit':'ثبت',    
    'filter':'فیلتر کن',
    'search_placeholder':'جستجو...',
    'contains_words': 'شامل حروف',
    'save':'ذخیره',
    'filter_and_search':'فیلتر و جستجو',
    'tags': 'برچسب ها',
    'is_private':'خصوصی',
    'speakers': 'صحبت کنندگان',
    'listeners': 'شنوندگان',
    'moderator': 'مدیر',
    'listener': 'شنونده',
    'presenter': 'ارائه دهنده',
    'speaker': 'صحبت کننده',
    'calendar':'تقویم',
    'enter_room': 'ورود به جلسه',
    'default_is_private_info':'کاربران نمیتوانند خودشان در رویداد ها یا نشست های خصوصی عضو شوند و صرفا باید دعوت شوند',
  },

  'english' : {
    'overview': 'Overview',
    'events': 'Events',
    'home': 'Home',
    'meetings': 'Meetings',
    'users': 'Users',
    'your_country': 'Your Country',
    'bio': 'Bio',
    'write_about_yourself': 'Write about yourself',
    'complete_your_profile':'Complete your profile',
    'continue': 'Continue',
    'profiles': 'Users',
    'settings':'Settings',

    'event_detail':'Details',
    'event_title':"Event's title",
    'event_info':'More info',
    'event_type':'Event type',
    'event':'Event',
    'create_event': 'Create Event',
    'create_event_page':'Create Event',
    'in_person': 'In person',
    'online': 'Online',
    'hybrid': 'Hybrid',
    'filter_events':'Filter events',
    'event_start_date': 'Starts at',
    'event_end_date': 'Ends at',

    'abilities':'امکانات کاربران',
    'restrictions':'محدودیت های کاربران',
    'reports':'گزارشات',
    '':'',
    
    'meeting_info': 'More info',
    'meeting_title':'Meeting title',
    'meeting_detail':'Details',
    'meeting_type': 'Meeting tpe',
    'meeting_capacity': 'Meeting capacity',
    'meeting_external_link': 'External link',
    'meeting_start_time': 'Starts at',
    'meeting_end_time': 'Ends at',
    'related_to_event': 'Related to event',
    'create_meeting':'Create meeting',
    'create_meeting_page':'Create meeting',
    'online_external': 'Online/External',
    'filter_meetings': 'Filter & search meetings',
    'service_type':'Service type',
    'internal': 'Internal collaboration room',
    'bigblue': 'BigBlueButton',
    

    'exhibition_info':'More info',
    'exhibition_detail': 'Details',
    'exhibition_title': 'Title',
    'related_to_event': 'Event',
    'create_exhibition': 'Create booth',
    'create_exhibition_page':'Create booth',
    'exhibitions': 'Exhibitions',
    'stations': 'Stations',
    'enter_room_with_admin': 'Negotiate with Exhibitor',

    'choose_participants': 'Choose participants',
    'participants': 'Participants',
    'add_participants': 'Add participants',

    'pages':'Pages',
    'page_content':'Page content',
    'page_title': 'Page title',
    'create_page': 'Create page',
    'default_page': 'Deafult page',
    'default_page_info': 'Show this page as default',

    'create_upload': 'Upload resource',
    'upload_title': 'Resource title',
    'default_is_private_upload': 'This resource is private. Only moderators can view this.',
    'cover': 'Cover image',
    'file' : 'File',
    'video': 'Video',
    'choose_file': 'Choose file',
    'resources': 'Resources',
    'all': 'All',
    'resource_type': 'Resource type',

    'q_and_a_s': 'Questions & answers',
    'create_question_page': 'Submit question',
    'create_question':'Ask your question',
    'question_content': 'Content',
    'default_is_private_question': 'Only moderators can view the question',
    '':'',

    'chats': 'Chats',
    'details':'Details',
    'welcome': 'Welcome',
    'welcome_note': 'In this application, you can participate in the exisiting events or you can manage your own events.',
    'sign_up_now': 'Sign up now',
    'your_email':'Email',
    'your_name': 'Fullname',
    'choose_password': 'Choose pasword',
    'repeat_password': 'Repeat password',
    'password_rule': 'Password should be at least 8 character',
    'sign_up_and_continue': 'Sign up and continue',
    'login_if_registered': 'If you already registered',
    'if_not_registered': 'If you did not register',
    'login':'Login',
    'sign_up': 'Sign up',
    'password': 'Password',
    'enter_bigblue_room': 'Enter room (BBB)',
    '':'',

    'poll_content':'متن پرسش نظرسنجی',
    'single_select':'چندگزینه تک انتخاب',
    'multiple_select':'چند گزینه چند انتخاب',
    'star':'ستاره',
    'binary':'بلی/خیر',
    'trinary':'موافق/مخالف/ممتنع',
    'answer_type':'نوع پاسخ',
    'select_content':'پاسخ های چند گزینه ای',
    'separate_with_enter':'با دکمه enter پاسخ ها را جدا کنید.',
    'polls':'Polls',

    'just_listen_click': 'If you just want to listen, click here!',
    'piano1': 'Piano 1',
    'piano2': 'Piano 2',
    'ended':'Ended',
    'quran':'Quran',
    'applause1': 'Applause 1',
    'applause2': 'Applause 2',
    'laugh':'خنده',
    'laughing':'قهقهه',
    'snoring': 'Snoring',
    'throat': 'Clear throat',
    'footsteps': 'footsteps',
    'play_sound': 'Play sound',
    'remaining':'Remaining',
    'seconds':'Seconds',
    'anthem-iran': 'IRI National Anthem',
    'Permission denied': 'Permission to webcam/microphone is denied',
    'sata': 'SATA',
    'close': 'Close',
    'maximize': 'Maximize',
    'yes': 'Yes',
    'no': 'No',
    'abstention':'Abstention',
    'viewers': 'Viewers',
    'my_calendar':'My calendar',
    'registeration': 'Status',
    'registered': 'Registered',
    'not_registered': 'Not registered',
    'are_you_sure':'Are you sure?',
    'delete':'Delete',
    'true':'True',
    'false':'False',
    'create_event':'Create Event',
    'create_exhibition': 'Create Booth',
    'modify_ability': 'Modify user abilities',
    'administration': 'Administration',
    'view':'View',
    'out_of_time': 'Out of time',
    'room_is_full':'Room is full',
    'unregister': 'Leave',
    'register': 'Register',
    'check_your_spam_folder': 'در صورت عدم مشاهده، پوشه spam را هم بررسی کنید',
    'your_account_is_not_verified': 'لطفا کد تایید را که برای شما ایمیل شده است وارد کنید',
    'verfication_code': 'Verification code',
    'email': 'Email',
    'name': 'Full name',
    'password':'Password',
    'password_confirmation': 'Password confirmation',
    'file':'File',
    'info': 'Info',
    'title': 'Title',
    'the_following_should_not_be_empty': 'The following field(s) cannot be empty',
    'error': 'Error',
    'no_result_to_show': 'No results to show',
    'try_adjusting_your_search': 'Adjust your search',
    'cas':'احراز هویت مرکزی',
    'more':'More',
    'date_from':'From date',
    'date_to':'To date',
    'logout': 'Logout',
    'write_something': 'Write something ...',
    'provide_following_info':'Fill out the following items',
    'cancel':'Cancel',
    'submit':'Submit',    
    'filter': 'Filter results',
    'search_placeholder':'Search ...',
    'contains_words': 'Contains words',
    'save':'Save',
    'filter_and_search':'Filter results',
    'tags': 'Tags',
    'is_private': 'Private',
    'speakers': 'Speakers',
    'listeners': 'Listeners',
    'moderator': 'Moderator',
    'listener': 'Listener',
    'presenter': 'Presenter',
    'speaker': 'Speaker',
    'calendar': 'Calendar',
    'enter_room': 'Enter room',
    'default_is_private_info': 'User cannot register themselves. They should be added by moderators',
  }

}
