export const dict = {
  fa : {
    'overview': 'نمای کلی',
    'events': 'رویدادها',
    'home': 'خانه',
    'meetings': 'نشست ها',
    'users': 'کاربران',

    'event_detail':'جزئیات رویداد',
    'event_title':'عنوان رویداد',
    'event_info':'شرح رویداد',
    'event_type':'نوع رویداد',
    'event':'رویداد',
    'create_event':'ایجاد رویداد',
    'create_event_page':'ایجاد رویداد',
    'in_person': 'حضوری',
    'online': 'برخط',
    'hybrid': 'تلفیقی',

    'meeting_info':'شرح نشست',
    'meeting_title':'عنوان نشست',
    'meeting_detail':'جزئیات نشست',
    'meeting_type':'نوع نشست',
    'meeting_capacity': 'ظرفیت نشست',
    'meeting_external_link': 'لینک نشست',
    'meeting_start_time': 'زمان شروع',
    'meeting_end_time': 'زمان پایان',
    'related_to_event': 'نشستی از رویداد',
    'create_meeting':'ایجاد نشست',
    'create_meeting_page':'ایجاد نشست',
    'online_external': 'برخط بیرونی',
    
    'choose_participants': 'شرکت کنندگان موردنظر را انتخاب کنید',
    'participants':'شرکت کنندگان',
    'add_participants': 'افزودن شرکت کننده',

    'pages':'صفحات',
    'page_content':'محتوای صفحه',
    'page_title':'عنوان صفحه',
    'create_page':'ایجاد صفحه',
    'default_page':'صفحه پیش فرض',
    'default_page_info':'این صفحه به عنوان پیش فرص در نشست نمایش داده شود',

    'write_something':'اینجا بنویسید ...',
    'provide_following_info':'اطلاعات زیر را تکمیل کنید',
    'cancel':'انصراف',
    'submit':'ثبت',    
    'search_placeholder':'جستجو...',
    'tags': 'برچسب ها',
    'is_private':'خصوصی',
    'speakers': 'صحبت کنندگان',
    'listeners': 'شنوندگان',
    'enter_room': 'ورود به جلسه',
    'default_is_private_info':'کاربران نمیتوانند خودشان در رویداد ها یا نشست های خصوصی عضو شوند و صرفا باید دعوت شوند',
  }

}
